_wandb:
    value:
        cli_version: 0.25.0
        e:
            ohpj18ij88o2apxkk8g0pxh5yxsztlqt:
                codePath: src/main.py
                codePathLocal: src/main.py
                email: jason12stock@gmail.com
                executable: /Users/stock/Development/research/stockeh/geometry-flow-interp/.venv/bin/python3
                host: Jasons-MacBook-Pro.local
                os: macOS-15.7-arm64-arm-64bit-Mach-O
                program: /Users/stock/Development/research/stockeh/geometry-flow-interp/src/main.py
                python: CPython 3.13.3
                root: /Users/stock/Development/research/stockeh/geometry-flow-interp
                startedAt: "2026-02-23T20:17:32.534666Z"
                writerId: ohpj18ij88o2apxkk8g0pxh5yxsztlqt
        m: []
        python_version: 3.13.3
        t:
            "1":
                - 1
                - 41
            "2":
                - 1
                - 41
            "3":
                - 13
                - 16
            "4": 3.13.3
            "5": 0.25.0
            "12": 0.25.0
            "13": darwin-arm64
batch_size:
    value: 256
checkpoint_dir:
    value: checkpoints
checkpoint_interval:
    value: 10
cosine:
    value: false
epochs:
    value: 500
experiment:
    value: default
grad_norm:
    value: 1
learning_rate:
    value: 0.001
offline:
    value: false
pca_dim:
    value: null
resume:
    value: false
unique_locations:
    value: false
val_split:
    value: 0.2
